services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tcu_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    volumes:
      - .:/app
    command: >
      gunicorn tcubackend.wsgi:application
      --bind 0.0.0.0:8000
      --workers=4
