# Generated by Django 5.0.2 on 2024-06-20 23:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InternshipApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("twitter_handle", models.CharField(max_length=255)),
                ("linkedin", models.URLField(max_length=255)),
                ("skill", models.CharField(max_length=255)),
                ("experience", models.TextField()),
                ("about_skill", models.TextField()),
                (
                    "certificate",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                ("commitment", models.BooleanField()),
                ("birthdate", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
