# Generated by Django 5.0.6 on 2024-07-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internship", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internshipapplication",
            name="certificate",
            field=models.FileField(
                blank=True, max_length=500, null=True, upload_to="certificates/"
            ),
        ),
    ]
