# Generated by Django 5.1.5 on 2025-02-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_alter_internshipapplication_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='github_link',
            field=models.URLField(default='', max_length=255),
        ),
    ]
