# Generated by Django 5.1.5 on 2025-03-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_internshipapplication_github_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='github_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='linkedin',
            field=models.CharField(max_length=255),
        ),
    ]
