# Generated by Django 5.1.5 on 2025-03-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_alter_internshipapplication_github_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
