# Generated by Django 5.1.5 on 2025-03-19 21:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_alter_internshipapplication_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='certificate',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificate'),
        ),
    ]
